# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-LazyACL
version:      0.04
version_from: lib/Data/LazyACL.pm
installdirs:  site
requires:
    Math::BigInt:                  0
    Readonly:                      0
    Test::Exception:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
